---
title: "TA"
author: "Li Ying"
date: "14 June 2015"
output: html_document
---
### Load Data
```{r}
library(xlsx)

#Load Dospert Original Survey Result (RISK part)
dospertRisk<-read.xlsx("./Dospert_Score_Risk_Association_Survey.xls",
sheetIndex=4,header=TRUE,colIndex=2:42,rowIndex=3:87)
names<-paste("Q",1:40,sep="")
colnames(dospertRisk)<-c("participants",names)

#Load Dospert Original Survey Result (BENEFIT part)
dospertBenefit<-read.xlsx("./Dospert_Score_Risk_Association_Survey.xls",
sheetIndex=5,header=TRUE,colIndex=2:42,rowIndex=3:87)
colnames(dospertBenefit)<-c("participants",names)

#Load Dospert coefficient
coef<-read.xlsx("./Dospert_Score_Risk_Association_Survey.xls",
sheetIndex=1,header=TRUE,colIndex=4:5,rowIndex=4:44)
colnames(coef)<-c("benefit","risk")
#change data type from factor to numeric
coef$benefit<-sub("\\,",".",coef$benefit)
coef$risk<-sub("\\,",".",coef$risk)
coef<-apply(coef,2,as.numeric)

#Reset coef to 1, since coefficient computation is wrong. 
coef<-data.frame(matrix(rep(1,80),ncol=2))
colnames(coef)<-c("benefit","risk")

#Read Free Association
freeAssoc<-read.csv("./freeAssociation.csv",na.strings="NA",colClasses="character")
# set NULL to NA
freeAssoc<-freeAssoc[-1,]
# set NULL to NA
for (i in 1:nrow(freeAssoc)){
index<-nchar(freeAssoc[i,])==0 # the subjec of nchar() must be a vector, not data.frame
freeAssoc[i,index]<-NA
}
```

###Calculate coefficient *Score 
```{r}
# Benefit calculation
benefit<-matrix(coef[,"benefit"])
risk<-matrix(coef[,"risk"])

benefit[is.na(benefit)]<-0
risk[is.na(risk)]<-0

dosBenefit<-as.matrix(dospertBenefit[,-1])
dosBenefit[is.na(dosBenefit)]<-0

dim(dosBenefit);dim(benefit)
weightedBenefit<-dosBenefit%*%benefit

# Risk calculation
dosRisk<-as.matrix(dospertRisk[,-1])
dosRisk[is.na(dosRisk)]<-0

weightedRisk<-dosRisk%*%risk
```

### Calculate Dospert Aggregate Score 
## Excel sheet get the answer wrong, sheet=benefit
```{r}
dospertAgg<-data.frame(benefit=weightedBenefit,risk=weightedRisk)
dospertAgg$DospertScore<-apply(dospertAgg,1,sum)
# set 0 to NA
dospertAgg[dospertAgg==0]<-NA
```

### Pairwise multiplication of coefficient and answers to each questions
```{r}
detailRiskW<-dosRisk
for (i in 1:nrow(dosRisk)){
detailRiskW[i,]<-t(risk)*dosRisk[i,]
}

detailBenefitW<-dosBenefit
for (i in 1:nrow(dosBenefit)){
detailBenefitW[i,]<-t(benefit)*dosBenefit[i,]
}
```

### calculate by each domain 
```{r}
f<-gl(5,8)
n<-nrow(detailRiskW)
domainAggRisk<-matrix(data=rep(0,5*84),ncol=5)

for (i in 1:n){
domainAggRisk[i,]<-tapply(detailRiskW[i,],f,sum)}
colnames(domainAggRisk)<-c("financial","ethical","health","recreational","social")
head(domainAggRisk)

### Benefit
domainAggBenefit<-matrix(data=rep(0,5*84),ncol=5)

for (i in 1:n){
domainAggBenefit[i,]<-tapply(detailBenefitW[i,],f,sum)}
colnames(domainAggBenefit)<-c("financial","ethical","health","recreational","social")
head(domainAggBenefit)
```

### Exploring relationships between domains
```{r}
library(ggplot2)
# Transfor back to data.frame from matrix for plotting, remove NA observations
DFdomainAggBenefit<-data.frame(domainAggBenefit)
DFdomainAggBenefit[DFdomainAggBenefit == 0] <- NA
DFdomainAggBenefit<-na.omit(DFdomainAggBenefit)

ggplot(DFdomainAggBenefit, aes(financial,ethical))+geom_point()
ggplot(DFdomainAggBenefit, aes(financial,recreational))+geom_point()

# regress against financial
model1<-lm(financial~.,data=DFdomainAggBenefit)
summary(model1)
# all are not significant at 0.05 level

# regress against ethical
model2<-lm(ethical~.,data=DFdomainAggBenefit)
summary(model2)
# health is significant at 0.05 significant level

# regress against health
model3<-lm(health~.,data=DFdomainAggBenefit)
summary(model3)
# recreational is significant at 0.01 significant level,ethical is significant at 0.05 level

# regress against recreational
model4<-lm(recreational~.,data=DFdomainAggBenefit)
summary(model4)
# health is significant at 0.01 significant level,social is significant at 0.01 level

with(DFdomainAggBenefit,cor.test(recreational,health))
with(DFdomainAggBenefit,cor.test(recreational,social))
with(DFdomainAggBenefit,cor.test(health,ethical))
```

```{r}
name<-1:160
colnames(freeAssoc)<-c("participant",name)
x<-as.character(freeAssoc[1,]);  x<-data.frame(table(x));  x<-x[order(-x$Freq),]
head(x,10)
```

### Whether scores follows normal disrtibution
```{r whether score follows normal}
library(ggplot2)
par(mfrow=c(1,2))
hist(dospertAgg$DospertScore,breaks=10)
qqnorm(dospertAgg$DospertScore, col="blue");qqline(dospertAgg$DospertScore, col=2)
dev.off()
```

```{r preprocess data with BoxCox transformation}
library(caret)
preObj<-preProcess(dospertAgg,method=c("BoxCox"))
BCdospertAgg<-predict(preObj,dospertAgg)
# Plot Histogtam and QQ plot
par(mfrow=c(1,2));hist(BCdospertAgg$DospertScore);qqnorm(BCdospertAgg$DospertScore);
qqline(BCdospertAgg$DospertScore, col=2)
```


### A more formal way to exam normality
```{r}
library(moments)
jarque.test(na.omit(dospertAgg)$DospertScore)

kurtosis.test <- function (x) {
m4 <- sum((x-mean(x))^4)/length(x)
s4 <- var(x)^2
kurt <- (m4/s4) - 3
sek <- sqrt(24/length(x))
totest <- kurt/sek
pvalue <- pt(totest,(length(x)-1))
pvalue 
}


skew.test <- function (x) {
m3 <- sum((x-mean(x))^3)/length(x)
s3 <- sqrt(var(x))^3
skew <- m3/s3
ses <- sqrt(6/length(x))
totest <- skew/ses
pt(totest,(length(x)-1))
pval <- pt(totest,(length(x)-1))
pval
}

kurtosis.test(na.omit(dospertAgg)$DospertScore)
skew.test(na.omit(dospertAgg)$DospertScore)
```
